# The URL the site will be built for
base_url = "https://esp32.art"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Default language
default_language = "en"

# Syntax highlighting for code blocks
[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark" # You can change this to any Zola-supported theme

# RSS generation and pagination
generate_rss = true
rss_limit = 20
paginate_by = 10

# Custom extra variables
[extra]
entries_section = "entries"

# Taxonomies for filtering
taxonomies = [
  { name = "tags", rss = true, paginate_by = 10 },
  { name = "boards", rss = false, paginate_by = 10 },
  { name = "mcus", rss = false, paginate_by = 10 }
]

# Language-specific metadata
[languages.en]
title = "ESP32 Art"
description = "A community-curated gallery of creative ESP32 demos, games, and applications."

# Output directory for the built site
output_dir = "public"

# Search index configuration
[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_content = true
include_taxonomies = ["tags", "boards", "mcus"]
