name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' depending on your repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      - name: Build the site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: esp32.art